permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 鲍阳
  email: michaelbockson@gmail.com
  link: http://baoyangbob.github.io/
# weibo: http://weibo.com/yansu0711
  github: http://github.com/BaoyangBob

# 站点信息
title: 鲍阳的博客 
description: 鲍阳的博客
url: http://baoyangbob.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://img.my.csdn.net/uploads/201601/10/1452435996_9050.png
favicon: http://img.my.csdn.net/uploads/201601/10/1452435996_9050.png

# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# disqus 设置
disqus:
  shortname: httpbaoyangbobgithubio